/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ec-api/apis/deployment/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrafficFilterAssociations implements TrafficFilterAssociationInterface
type FakeTrafficFilterAssociations struct {
	Fake *FakeDeploymentV1alpha1
	ns   string
}

var trafficfilterassociationsResource = schema.GroupVersionResource{Group: "deployment.ec.kubeform.com", Version: "v1alpha1", Resource: "trafficfilterassociations"}

var trafficfilterassociationsKind = schema.GroupVersionKind{Group: "deployment.ec.kubeform.com", Version: "v1alpha1", Kind: "TrafficFilterAssociation"}

// Get takes name of the trafficFilterAssociation, and returns the corresponding trafficFilterAssociation object, and an error if there is any.
func (c *FakeTrafficFilterAssociations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TrafficFilterAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(trafficfilterassociationsResource, c.ns, name), &v1alpha1.TrafficFilterAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficFilterAssociation), err
}

// List takes label and field selectors, and returns the list of TrafficFilterAssociations that match those selectors.
func (c *FakeTrafficFilterAssociations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TrafficFilterAssociationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(trafficfilterassociationsResource, trafficfilterassociationsKind, c.ns, opts), &v1alpha1.TrafficFilterAssociationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TrafficFilterAssociationList{ListMeta: obj.(*v1alpha1.TrafficFilterAssociationList).ListMeta}
	for _, item := range obj.(*v1alpha1.TrafficFilterAssociationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested trafficFilterAssociations.
func (c *FakeTrafficFilterAssociations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(trafficfilterassociationsResource, c.ns, opts))

}

// Create takes the representation of a trafficFilterAssociation and creates it.  Returns the server's representation of the trafficFilterAssociation, and an error, if there is any.
func (c *FakeTrafficFilterAssociations) Create(ctx context.Context, trafficFilterAssociation *v1alpha1.TrafficFilterAssociation, opts v1.CreateOptions) (result *v1alpha1.TrafficFilterAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(trafficfilterassociationsResource, c.ns, trafficFilterAssociation), &v1alpha1.TrafficFilterAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficFilterAssociation), err
}

// Update takes the representation of a trafficFilterAssociation and updates it. Returns the server's representation of the trafficFilterAssociation, and an error, if there is any.
func (c *FakeTrafficFilterAssociations) Update(ctx context.Context, trafficFilterAssociation *v1alpha1.TrafficFilterAssociation, opts v1.UpdateOptions) (result *v1alpha1.TrafficFilterAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(trafficfilterassociationsResource, c.ns, trafficFilterAssociation), &v1alpha1.TrafficFilterAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficFilterAssociation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTrafficFilterAssociations) UpdateStatus(ctx context.Context, trafficFilterAssociation *v1alpha1.TrafficFilterAssociation, opts v1.UpdateOptions) (*v1alpha1.TrafficFilterAssociation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(trafficfilterassociationsResource, "status", c.ns, trafficFilterAssociation), &v1alpha1.TrafficFilterAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficFilterAssociation), err
}

// Delete takes name of the trafficFilterAssociation and deletes it. Returns an error if one occurs.
func (c *FakeTrafficFilterAssociations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(trafficfilterassociationsResource, c.ns, name), &v1alpha1.TrafficFilterAssociation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrafficFilterAssociations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(trafficfilterassociationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TrafficFilterAssociationList{})
	return err
}

// Patch applies the patch and returns the patched trafficFilterAssociation.
func (c *FakeTrafficFilterAssociations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrafficFilterAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trafficfilterassociationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TrafficFilterAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficFilterAssociation), err
}
