/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-ec-api/apis/deployment/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeElasticsearchKeystores implements ElasticsearchKeystoreInterface
type FakeElasticsearchKeystores struct {
	Fake *FakeDeploymentV1alpha1
	ns   string
}

var elasticsearchkeystoresResource = schema.GroupVersionResource{Group: "deployment.ec.kubeform.com", Version: "v1alpha1", Resource: "elasticsearchkeystores"}

var elasticsearchkeystoresKind = schema.GroupVersionKind{Group: "deployment.ec.kubeform.com", Version: "v1alpha1", Kind: "ElasticsearchKeystore"}

// Get takes name of the elasticsearchKeystore, and returns the corresponding elasticsearchKeystore object, and an error if there is any.
func (c *FakeElasticsearchKeystores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ElasticsearchKeystore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(elasticsearchkeystoresResource, c.ns, name), &v1alpha1.ElasticsearchKeystore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchKeystore), err
}

// List takes label and field selectors, and returns the list of ElasticsearchKeystores that match those selectors.
func (c *FakeElasticsearchKeystores) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ElasticsearchKeystoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(elasticsearchkeystoresResource, elasticsearchkeystoresKind, c.ns, opts), &v1alpha1.ElasticsearchKeystoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ElasticsearchKeystoreList{ListMeta: obj.(*v1alpha1.ElasticsearchKeystoreList).ListMeta}
	for _, item := range obj.(*v1alpha1.ElasticsearchKeystoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested elasticsearchKeystores.
func (c *FakeElasticsearchKeystores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(elasticsearchkeystoresResource, c.ns, opts))

}

// Create takes the representation of a elasticsearchKeystore and creates it.  Returns the server's representation of the elasticsearchKeystore, and an error, if there is any.
func (c *FakeElasticsearchKeystores) Create(ctx context.Context, elasticsearchKeystore *v1alpha1.ElasticsearchKeystore, opts v1.CreateOptions) (result *v1alpha1.ElasticsearchKeystore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(elasticsearchkeystoresResource, c.ns, elasticsearchKeystore), &v1alpha1.ElasticsearchKeystore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchKeystore), err
}

// Update takes the representation of a elasticsearchKeystore and updates it. Returns the server's representation of the elasticsearchKeystore, and an error, if there is any.
func (c *FakeElasticsearchKeystores) Update(ctx context.Context, elasticsearchKeystore *v1alpha1.ElasticsearchKeystore, opts v1.UpdateOptions) (result *v1alpha1.ElasticsearchKeystore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(elasticsearchkeystoresResource, c.ns, elasticsearchKeystore), &v1alpha1.ElasticsearchKeystore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchKeystore), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeElasticsearchKeystores) UpdateStatus(ctx context.Context, elasticsearchKeystore *v1alpha1.ElasticsearchKeystore, opts v1.UpdateOptions) (*v1alpha1.ElasticsearchKeystore, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(elasticsearchkeystoresResource, "status", c.ns, elasticsearchKeystore), &v1alpha1.ElasticsearchKeystore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchKeystore), err
}

// Delete takes name of the elasticsearchKeystore and deletes it. Returns an error if one occurs.
func (c *FakeElasticsearchKeystores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(elasticsearchkeystoresResource, c.ns, name), &v1alpha1.ElasticsearchKeystore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeElasticsearchKeystores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(elasticsearchkeystoresResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ElasticsearchKeystoreList{})
	return err
}

// Patch applies the patch and returns the patched elasticsearchKeystore.
func (c *FakeElasticsearchKeystores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ElasticsearchKeystore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(elasticsearchkeystoresResource, c.ns, name, pt, data, subresources...), &v1alpha1.ElasticsearchKeystore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchKeystore), err
}
